name: qr_attendance
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^5.2.1
  image_picker:
  qr_flutter: ^4.1.0
  hive: ^2.2.3
  http: ^1.2.2
  pin_code_fields: ^8.0.1
  error_handeler_flutter: ^0.0.7
  encrypt: ^5.0.3
  path_provider: ^2.1.4
  firebase_core: ^3.4.1
  cloud_firestore: ^5.4.1
  fluttertoast: ^8.2.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
